trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'Azure-Service-Connection'
  appName: 'kavya-11'

steps:
- script: echo "Pipeline running successfully"
  displayName: Test Build 